# This is a basic workflow to help you get started with Actions

name: Deploy Site
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install surge and fire deployment 
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install -g surge tailwindcss postcss-cli autoprefixer
      - run: surge ./ ${{ secrets.SURGE_DOMAIN  }} --token ${{ secrets.SURGE_TOKEN }}
